version: "3.4"

networks:
  frontend:
    external: true
  backend:
    external: true

services:
  postgresql:
    image: docker.io/library/postgres:12-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/db/${CONTNAME}/database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PG_PASS:?database password required}
      POSTGRES_USER: ${PG_USER:-authentik}
      POSTGRES_DB: ${PG_DB:-authentik}
    env_file:
      - stack.env
    networks:
      - backend
      
  redis:
    image: docker.io/library/redis:alpine
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/container/${CONTNAME}/redis:/data
    networks:
      - backend
      
  server:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2023.8.3}
    restart: unless-stopped
    command: server
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/container/${CONTNAME}/media:/media
      - /docker/container/${CONTNAME}/custom-templates:/templates
    env_file:
      - stack.env
    ports:
      - "${COMPOSE_PORT_HTTP:-9000}:9000"
      - "${COMPOSE_PORT_HTTPS:-9443}:9443"
    depends_on:
      - postgresql
      - redis
    networks:
      - frontend
      - backend
    labels:
      - "traefik.enable=${TRAEFIK}"
      - "traefik.http.routers.${CONTNAME}.entrypoints=http"
      - "traefik.http.routers.${CONTNAME}.rule=Host(`${DOMAIN}`)"
      - "traefik.http.middlewares.${CONTNAME}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.${CONTNAME}.middlewares=${CONTNAME}-https-redirect"
      - "traefik.http.routers.${CONTNAME}-secure.entrypoints=https"
      - "traefik.http.routers.${CONTNAME}-secure.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.${CONTNAME}-secure.tls=true"
      - "traefik.http.routers.${CONTNAME}-secure.service=${CONTNAME}"
      - "traefik.http.services.${CONTNAME}.loadbalancer.server.port=9000"
      - "traefik.docker.network=frontend"
      
  worker:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2023.8.3}
    restart: unless-stopped
    command: worker
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
    # `user: root` and the docker socket volume are optional.
    # See more for the docker socket integration here:
    # https://goauthentik.io/docs/outposts/integrations/docker
    # Removing `user: root` also prevents the worker from fixing the permissions
    # on the mounted folders, so when removing this make sure the folders have the correct UID/GID
    # (1000:1000 by default)
    user: root
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker/container/${CONTNAME}/media:/media
      - /docker/container/${CONTNAME}/certs:/certs
      - /docker/container/${CONTNAME}/custom-templates:/templates
    env_file:
      - stack.env
    depends_on:
      - postgresql
      - redis
    networks:
      - backend
