version: "3"

networks:
  frontend:
    external: true # add this if the network is already existing!

services:
  cloudflare-ddns:
    container_name: ${CONTNAME}
    hostname: ${CONTNAME}
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      - API_KEY=${CF_API_TOKEN}
      - ZONE=${DOMAINS}
#      - SUBDOMAIN=subdomain
      - PROXIED=${PROXIED}
#    network_mode: host
    networks:
      - frontend
    dns: 
      - 10.13.37.250