version: '3'

networks:
  frontend:
    external: true # add this if the network is already existing!
    
services:
  cups:
    image: kimostberg/cups:latest
    container_name: ${CONTNAME}
#    network_mode: host
    ports:
      - "631:631"
    restart: unless-stopped
    volumes:
      - /var/run/dbus:/var/run/dbus
      - /docker/container/${CONTNAME}/etc:/etc/cups
      - /docker/container/${CONTNAME}/config:/config
      - /docker/container/${CONTNAME}/services:/services
    devices:
      - /dev/bus:/dev/bus
#      - /dev/usb:/dev/usb
    environment:
      - CUPSADMIN=${CUPS_ADMIN}
      - CUPSPASSWORD=${CUPS_PASSWORD}
    networks:
      - frontend
    dns: 172.20.0.250