version: '3'

volumes:
  config:
  services:
  etc:

networks:
  frontend:
    external: true # add this if the network is already existing!
    
services:
  cups:
    image: kimostberg/cups:latest
    container_name: ${CONTNAME}
#    network_mode: host
    ports:
      - "631:631"
    restart: unless-stopped
    volumes:
      - /var/run/dbus:/var/run/dbus
      - etc:/etc/cups
      - config:/config
      - services:/services
    devices:
      - /dev/bus:/dev/bus
      - /dev/usb:/dev/usb
    environment:
      - CUPSADMIN=${CUPS_ADMIN}
      - CUPSPASSWORD=${CUPS_PASSWORD}
    networks:
      - frontend