version: '3'

networks:
  frontend:
    external: true # add this if the network is already existing!
    
services:
  cups:
    image: kimostberg/cups:latest
    container_name: ${CONTNAME}
#    network_mode: host
    ports:
      - "${WEBPORT}:631"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/dbus:/var/run/dbus
      - /docker/container/${CONTNAME}/config:/config
      - /docker/container/${CONTNAME}/services:/services
      - /docker/container/${CONTNAME}/etc:/etc/cups
    devices:
      - /dev/bus:/dev/bus
      - /dev/usb:/dev/usb
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - CUPSADMIN=${CUPS_ADMIN}
      - CUPSPASSWORD=${CUPS_PASSWORD}
    labels:
      - "traefik.enable=${TRAEFIK}"
      - "traefik.http.routers.${CONTNAME}.entrypoints=http"
      - "traefik.http.routers.${CONTNAME}.rule=Host(`${CONTNAME}.${DOMAIN}`)"
      - "traefik.http.middlewares.${CONTNAME}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.${CONTNAME}.middlewares=${CONTNAME}-https-redirect"
      - "traefik.http.routers.${CONTNAME}-secure.entrypoints=https"
      - "traefik.http.routers.${CONTNAME}-secure.rule=Host(`${CONTNAME}.${DOMAIN}`)"
      - "traefik.http.routers.${CONTNAME}-secure.tls=true"
      - "traefik.http.routers.${CONTNAME}-secure.service=${CONTNAME}"
      - "traefik.http.services.${CONTNAME}.loadbalancer.server.port=631"
      - "traefik.docker.network=frontend"
    networks:
      - frontend
    dns: 172.20.0.250