version: '3'

networks:
  frontend:
    external: true # add this if the network is already existing!
    
services:
  cups:
    image: ydkn/cups:latest
    container_name: ${CONTNAME}
    hostname: ${CONTNAME}
#    ports:
#      - "631:631"
    restart: unless-stopped
    volumes:
      - /var/run/dbus:/var/run/dbus
      - /container/${CONTNAME}/config:/etc/cups
#      - /container/${CONTNAME}/services:/services
#    devices:
#      - /dev/bus:/dev/bus
    environment:
#      - CUPSADMIN=${CUPS_ADMIN}
      - ADMIN_PASSWORD=${CUPS_PASSWORD}
    networks:
      - frontend