version: '3'

networks:
  frontend:
    external: true # add this if the network is already existing!
    
services:
  cups:
    image: kimostberg/cups-airprint
    container_name: ${CONTNAME}
    hostname: ${CONTNAME}
#    network_mode: host
    ports:
      - "631:631"
    restart: unless-stopped
    volumes:
      - /var/run/dbus:/var/run/dbus
      - /container/${CONTNAME}/etc/cups:/etc/cups
      - /container/${CONTNAME}/config:/config
      - /container/${CONTNAME}/services:/services
    devices:
      - /dev/bus:/dev/bus
    environment:
      - CUPSADMIN=${CUPS_ADMIN}
      - CUPSPASSWORD=${CUPS_PASSWORD}
    networks:
      - frontend