version: '3'

networks:
  frontend:
    external: true # add this if the network is already existing!
    
services:
  cups:
    image: olbat/cupsd
    container_name: ${CONTNAME}
    hostname: ${CONTNAME}
#    ports:
#      - "631:631"
    restart: unless-stopped
    volumes:
      - /var/run/dbus:/var/run/dbus
#      - /container/${CONTNAME}/config:/config
#      - /container/${CONTNAME}/services:/services
#    devices:
#      - /dev/bus:/dev/bus
    environment:
      - CUPSADMIN=${CUPS_ADMIN}
      - CUPSPASSWORD=${CUPS_PASSWORD}
    networks:
      - frontend