version: "3.8"
services:
  dockge:
    container_name: dockge
    image: louislam/dockge:latest
    restart: unless-stopped
    ports:
      # Host Port : Container Port
      - 5001:5001
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data

      # If you want to use private registries, you need to share the auth file with Dockge:
      # - /root/.docker/:/root/.docker

      # Your stacks directory in the host (The paths inside container must be the same as the host)
      # ⚠️⚠️ If you did it wrong, your data could end up be written into a wrong path.
      # ✔️✔️✔️✔️ CORRECT: - /my-stacks:/my-stacks (Both paths match)
      # ❌❌❌❌ WRONG: - /docker:/my-stacks (Both paths do not match)
      - ${DOCKGE_PATH}:${DOCKGE_PATH}
    environment:
      # Tell Dockge where is your stacks directory
      - DOCKGE_STACKS_DIR=${DOCKGE_PATH}
    networks:
      - frontend
    env_file:
      - .env
networks:
  frontend:
    external: true