version: "2.1"

networks:
  frontend: 
    external: true # add this if the network is already existing!

services:
  duplicati:
    image: ghcr.io/linuxserver/duplicati
    container_name: ${CONTNAME}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - CLI_ARGS= ${CLI_ARGS}
    volumes:
      - /docker/container/${CONTNAME}:/config
      - /docker:/source
      - /backups:/backups
    ports:
      - 8200:8200
    restart: unless-stopped    
    networks:
      - frontend
    dns: 172.20.0.250