version: "2.1"

networks:
  frontend: 
    external: true # add this if the network is already existing!

volumes:
  config:

services:
  duplicati:
    image: ghcr.io/linuxserver/duplicati
    container_name: ${CONTNAME}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - CLI_ARGS= ${CLI_ARGS}
    volumes:
      - config:/config
      - /var/lib/docker/volumes:/source/docker/volumes
      - /backups/db:/source/db
    ports:
      - 8200:8200
    restart: unless-stopped    
    networks:
      - frontend
    dns: 172.20.0.250