version: "3"

networks:
  frontend: 
    external: true # add this if the network is already existing!

services:
  duplicati:
    image: ghcr.io/linuxserver/duplicati
    container_name: ${CONTNAME}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - CLI_ARGS= ${CLI_ARGS}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/container/${CONTNAME}/data:/config
      - /docker:/source
      - /backups:/backups
#    ports:
#      - 8200:8200
    restart: unless-stopped    
    networks:
      - frontend
    dns: 172.20.0.250
    labels:
      - "traefik.enable=${TRAEFIK}"
      - "traefik.http.routers.${CONTNAME}.entrypoints=http"
      - "traefik.http.routers.${CONTNAME}.rule=Host(`${CONTNAME}.${DOMAIN}`)"
      - "traefik.http.middlewares.${CONTNAME}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.${CONTNAME}.middlewares=${CONTNAME}-https-redirect"
      - "traefik.http.routers.${CONTNAME}-secure.entrypoints=https"
      - "traefik.http.routers.${CONTNAME}-secure.rule=Host(`${CONTNAME}.${DOMAIN}`)"
      - "traefik.http.routers.${CONTNAME}-secure.tls=true"
      - "traefik.http.routers.${CONTNAME}-secure.service=${CONTNAME}"
      - "traefik.http.services.${CONTNAME}.loadbalancer.server.port=8200"
      - "traefik.docker.network=frontend"