version: "2.1"

volumes:
  config:

services:
  duplicati:
    image: ghcr.io/linuxserver/duplicati
    container_name: ${CONTNAME}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - CLI_ARGS= ${CLI_ARGS}
    volumes:
      - config:/config
      - /backups:/backups
      - /var/lib/docker/volumes:/source/docker/volumes
      - /backups/db:/sources/db
    ports:
      - 8200:8200
    restart: unless-stopped