version: "3"
services:
    home-assistant:
        container_name: homeassistant
        privileged: true
        restart: unless-stopped
#        environment:
#            - TZ=MY_TIME_ZONE
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /docker/homeassistant/config:/config
            - /run/dbus:/run/dbus:ro
        networks:
            frontend:
                ipv4_address: 172.20.0.249
        ports:
            - 8123:8123
        image: homeassistant/home-assistant:stable

networks:
  frontend:
    external: true