version: '3'

networks:
  frontend: 
    external: true # add this if the network is already existing!
  backend:
    external: true # add this if the network is already existing!

services:
    db:
        container_name: ${CONTNAME}_db
        image: postgres:15
        volumes:
            - /docker/db/joplin/data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        restart: unless-stopped
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=joplin
            - POSTGRES_DB=joplin_db
        networks:
            - backend
    app:
        container_name: ${CONTNAME}
        image: joplin/server:latest
        depends_on:
            - db
        ports:
            - "22300:22300"
        restart: unless-stopped
        environment:
            - APP_PORT=22300
            - APP_BASE_URL=https://${APP_BASE_URL}
            - DB_CLIENT=pg
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DATABASE=joplin_db
            - POSTGRES_USER=joplin
            - POSTGRES_PORT=5432
            - POSTGRES_HOST=db
            - MAILER_ENABLED=${MAILER_ENABLED}
            - MAILER_HOST=${MAILER_HOST}
            - MAILER_PORT=${MAILER_PORT}
            - MAILER_SECURE=${MAILER_SECURE}
            - MAILER_AUTH_USER=${MAILER_AUTH_USER}
            - MAILER_AUTH_PASSWORD=${MAILER_AUTH_PASSWORD}
            - MAILER_NOREPLY_NAME=${MAILER_NOREPLY_NAME}
            - MAILER_NOREPLY_EMAIL=${MAILER_NOREPLY_EMAIL}
        networks:
            - frontend
            - backend
        dns: 172.20.0.250
        labels:
            - "traefik.enable=${TRAEFIK}"
            - "traefik.http.routers.${CONTNAME}.entrypoints=http"
            - "traefik.http.routers.${CONTNAME}.rule=Host(`${DOMAIN}`)"
            - "traefik.http.middlewares.${CONTNAME}-https-redirect.redirectscheme.scheme=https"
            - "traefik.http.routers.${CONTNAME}.middlewares=${CONTNAME}-https-redirect"
            - "traefik.http.routers.${CONTNAME}-secure.entrypoints=https"
            - "traefik.http.routers.${CONTNAME}-secure.rule=Host(`${DOMAIN}`)"
            - "traefik.http.routers.${CONTNAME}-secure.tls=true"
            - "traefik.http.routers.${CONTNAME}-secure.service=${CONTNAME}"
            - "traefik.http.services.${CONTNAME}.loadbalancer.server.port=80"
            - "traefik.docker.network=frontend"
