
version: '3'

networks:
  frontend: 
    external: true # add this if the network is already existing!
  backend:
    external: true # add this if the network is already existing!

services:
    mongodb:
        container_name: meshcentral_db
        restart: always
        image: mongo:latest
        expose:
            - 27017
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /docker/db/meshcentral/data:/data/db
            - /docker/db/meshcentral/config:/data/configdb
        networks:
            - backend

    meshcentral:
        restart: always
        container_name: meshcentral
        depends_on:
            - mongodb
        image: johann8/meshcentral
        ports:
            - 8086:443 #MeshCentral will moan and try everything not to use port 80, but you can also use it if you so desire, just change the config.json according to your needs
        environment:
            - HOSTNAME=meshcentral.example.com     #your hostname
            - REVERSE_PROXY=false     #set to your reverse proxy IP if you want to put meshcentral behind a reverse proxy
            - REVERSE_PROXY_TLS_PORT=443
            - IFRAME=false #set to true if you wish to enable iframe support
            - ALLOW_NEW_ACCOUNTS=true    #set to false if you want disable self-service creation of new accounts besides the first (admin)
            - WEBRTC=true  #set to true to enable WebRTC - per documentation it is not officially released with meshcentral, but is solid enough to work with. Use with caution
            - NODE_ENV=production
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /docker/container/meshcentral/data:/opt/meshcentral/meshcentral-data
            - /docker/container/meshcentral/user_files:/opt/meshcentral/meshcentral-files
            - /docker/container/meshcentral/backup:/opt/meshcentral/meshcentral-backup
        networks:
            - frontend
            - backend