version: '3'

networks:
  frontend:
    # add this if the network is already existing!
    external: true
  backend:
    external: true

services:

  nextcloud-app:
    image: nextcloud
    container_name: ${CONTNAME}
    hostname: ${CONTNAME}
    restart: unless-stopped
    volumes:
      - /container/${CONTNAME}/Data:/var/www/html
    environment:
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${CONTNAME}
      - MYSQL_USER=${CONTNAME}
      - MYSQL_HOST=172.21.0.51
      - TZ=${TZ}
    networks:
      - frontend
      backend:
        ipv4_address: 172.21.0.50 
    dns: 172.20.0.250


  nextcloud-db:
    container_name: "${CONTNAME}-db"
    hostname: "${CONTNAME}-db"
    image: linuxserver/mariadb:latest
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /container/${CONTNAME}/DB:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${CONTNAME}
      - MYSQL_USER=${CONTNAME}
      - TZ=${TZ}
    networks:
      backend:
        ipv4_address: 172.21.0.51