version: '3'

networks:
  frontend: 
    external: true # add this if the network is already existing!
  backend:
    external: true # add this if the network is already existing!

services:

  nextcloud-db:
    container_name: "${CONTNAME}-db"
    hostname: "${CONTNAME}-db"
    image: yobasystems/alpine-mariadb:latest
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    volumes:
      - /container/${CONTNAME}/DB:/var/lib/mysql
      - /container/${CONTNAME}/DB/config:/config
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${CONTNAME}
      - MYSQL_USER=${CONTNAME}
      - TZ=${TZ}
    networks:
      - backend

  nextcloud-app:
    image: nextcloud
    container_name: ${CONTNAME}
    hostname: ${CONTNAME}
    restart: unless-stopped
    links:
      - ${CONTNAME}-db
    volumes:
      - /container/${CONTNAME}/Data:/var/www/html
    environment:
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${CONTNAME}
      - MYSQL_USER=${CONTNAME}
      - MYSQL_HOST=${CONTNAME}-db
      - TZ=${TZ}
    networks:
      - frontend
      - backend
    dns: 172.20.0.250