version: '3'

networks:
  frontend: 
    external: true # add this if the network is already existing!
  backend:
    external: true # add this if the network is already existing!

services:

  nextcloud-db:
    container_name: nextcloud-db
    image: yobasystems/alpine-mariadb:latest
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/db/${CONTNAME}:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${CONTNAME}
      - MYSQL_USER=${CONTNAME}
    networks:
      - backend

  nextcloud-app:
    image: nextcloud
    container_name: nextcloud-app
    hostname: ${CONTNAME}
    restart: unless-stopped
    links:
      - nextcloud-db
#   ports: 
#     - 80:80
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/container/${CONTNAME}:/var/www/html
    environment:
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${CONTNAME}
      - MYSQL_USER=${CONTNAME}
      - MYSQL_HOST=$nextcloud-db
    networks:
      - frontend
      - backend
    dns: 172.20.0.250
    labels:
      - "traefik.enable=${TRAEFIK}"
      - "traefik.http.routers.${CONTNAME}.entrypoints=http"
      - "traefik.http.routers.${CONTNAME}.rule=Host(`${DOMAIN}`)"
      - "traefik.http.middlewares.${CONTNAME}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.${CONTNAME}.middlewares=${CONTNAME}-https-redirect"
      - "traefik.http.routers.${CONTNAME}-secure.entrypoints=https"
      - "traefik.http.routers.${CONTNAME}-secure.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.${CONTNAME}-secure.tls=true"
      - "traefik.http.routers.${CONTNAME}-secure.service=${CONTNAME}"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=443"
      - "traefik.docker.network=frontend"