version: '3'

networks:
  frontend:
    # add this if the network is already existing!
    external: true

services:
  pihole:
    container_name: ${HOSTNAME}
    image: cbcrowe/pihole-unbound:latest
    hostname: ${HOSTNAME}
    domainname: ${DOMAIN_NAME}
    ports:
    #  - 8443:443/tcp
      - 53:53/tcp
      - 53:53/udp
      - 8080:80/tcp
    #  - 5335:5335/tcp # Uncomment to enable unbound access on local server
    #  - 22/tcp # Uncomment to enable SSH
    environment:
      ServerIP: ${ServerIP}
      TZ: ${TZ}
      WEBPASSWORD: ${WEBPASSWORD}
      REV_SERVER: ${REV_SERVER}
      REV_SERVER_TARGET: ${REV_SERVER_TARGET}
      REV_SERVER_DOMAIN: ${REV_SERVER_DOMAIN}
      REV_SERVER_CIDR: ${REV_SERVER_CIDR}
    volumes:
      - /container/pihole/data:/etc/pihole:rw
      - /container/pihole/dnsmasq:/etc/dnsmasq.d:rw
    restart: unless-stopped
    networks:
      frontend:
        ipv4_address: ${PiHoleIP}