version: '3'

networks:
  frontend:
    external: true # add this if the network is already existing!
#  backend:
#    external: true # add this if the network is already existing!

services:
  pihole:
    container_name: ${CONTNAME}
    image: cbcrowe/pihole-unbound:latest
    hostname: ${CONTNAME}
    domainname: ${DOMAIN}
    ports:
    #  - 8443:443/tcp
      - 53:53/tcp
      - 53:53/udp
${PORTS}      - ${PIHOLE_WEBPORT}:80/tcp
    #  - 5335:5335/tcp # Uncomment to enable unbound access on local server
    #  - 22/tcp # Uncomment to enable SSH
    environment:
      FTLCONF_REPLY_ADDR4: ${FTLCONF_REPLY_ADDR4}
      WEBPASSWORD: ${WEBPASSWORD}
#      REV_SERVER: ${REV_SERVER}
#      REV_SERVER_TARGET: ${REV_SERVER_TARGET}
#      REV_SERVER_DOMAIN: ${REV_SERVER_DOMAIN}
#      REV_SERVER_CIDR: ${REV_SERVER_CIDR}
      PIHOLE_DNS_: 127.0.0.1#5335
      DNSSEC: ${DNSSEC}
      DNSMASQ_LISTENING: single
      WEBTHEME: ${WEBTHEME}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/container/${CONTNAME}/data:/etc/pihole:rw
      - /docker/container/${CONTNAME}/dnsmasq:/etc/dnsmasq.d:rw
    labels:
      - "traefik.enable=${TRAEFIK}"
      - "traefik.http.routers.${CONTNAME}.entrypoints=http"
      - "traefik.http.routers.${CONTNAME}.rule=Host(`${CONTNAME}.${DOMAIN}`)"
      - "traefik.http.middlewares.${CONTNAME}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.add-admin.addprefix.prefix=/admin"
      - "traefik.http.routers.${CONTNAME}.middlewares=pihole-https-redirect"
      - "traefik.http.routers.${CONTNAME}-secure.entrypoints=https"
      - "traefik.http.routers.${CONTNAME}-secure.rule=Host(`${CONTNAME}.${DOMAIN}`)"
      - "traefik.http.routers.${CONTNAME}-secure.tls=true"
      - "traefik.http.routers.${CONTNAME}-secure.service=pihole"
      - "traefik.http.services.${CONTNAME}.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
    restart: unless-stopped
    networks:
      frontend:
        ipv4_address: 172.20.0.250
#      backend:
#        ipv4_address: 172.21.0.250