version: '3'

networks:
  frontend:
    external: true # add this if the network is already existing!
#  backend:
#    external: true # add this if the network is already existing!

services:
  pihole:
    container_name: ${CONTNAME}
    image: cbcrowe/pihole-unbound:latest
    hostname: ${CONTNAME}
#    domainname: ${DOMAIN_NAME}
    ports:
    #  - 8443:443/tcp
      - 53:53/tcp
      - 53:53/udp
      - 8080:80/tcp
    #  - 5335:5335/tcp # Uncomment to enable unbound access on local server
    #  - 22/tcp # Uncomment to enable SSH
    environment:
      ServerIP: ${ServerIP}
      TZ: ${TZ}
      WEBPASSWORD: ${WEBPASSWORD}
#      REV_SERVER: ${REV_SERVER}
#      REV_SERVER_TARGET: ${REV_SERVER_TARGET}
#      REV_SERVER_DOMAIN: ${REV_SERVER_DOMAIN}
#      REV_SERVER_CIDR: ${REV_SERVER_CIDR}
    volumes:
      - /docker/container/${CONTNAME}/data:/etc/pihole:rw
      - /docker/container/${CONTNAME}/dnsmasq:/etc/dnsmasq.d:rw
    restart: unless-stopped
    networks:
      frontend:
        ipv4_address: 172.20.0.250
#      backend:
#        ipv4_address: 172.21.0.250
