version: "2.1"

networks:
  frontend: 
    external: true # add this if the network is already existing!
  backend:
    external: true # add this if the network is already existing!
    
services:    
  projectsend-db:
    image: yobasystems/alpine-mariadb:latest
    container_name: ${CONTNAME}-db
    hostname: ${CONTNAME}-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${CONTNAME}
      MYSQL_USER: ${CONTNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/db/${CONTNAME}:/var/lib/mysql #Database Volume Goes Here
    restart: unless-stopped
    networks:
      - backend

  projectsend-app:
    image: linuxserver/projectsend
    container_name: ${CONTNAME}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - MAX_UPLOAD=${MAX_UPLOAD}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/container/${CONTNAME}/config:/config #Config Volume Goes Here
      - /docker/container/${CONTNAME}/data:/data #File Storage Volume Goes Here
    links:
      - ${CONTNAME}-db
#    ports:
#      - 8010:80
    restart: unless-stopped
    networks:
      - frontend
      - backend
    dns: 172.20.0.250
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${CONTNAME}.entrypoints=http"
      - "traefik.http.routers.${CONTNAME}.rule=Host(`${DOMAIN}`)"
      - "traefik.http.middlewares.${CONTNAME}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.add-admin.addprefix.prefix=/admin"
      - "traefik.http.routers.${CONTNAME}.middlewares=pihole-https-redirect"
      - "traefik.http.routers.${CONTNAME}-secure.entrypoints=https"
      - "traefik.http.routers.${CONTNAME}-secure.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.${CONTNAME}-secure.tls=true"
      - "traefik.http.routers.${CONTNAME}-secure.service=pihole"
      - "traefik.http.services.${CONTNAME}.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"