version: "2.1"
services:
  resilio-sync:
    image: lscr.io/linuxserver/resilio-sync:latest
    container_name: resilio-sync
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/resilio-sync/config:/config
      - /docker/resilio-sync/downloads:/downloads
      - /docker/resilio-sync/sync:/sync
    ports:
      - 8888:8888
      - 55555:55555
    restart: unless-stopped
    networks:
      - frontend

networks:
  frontend: 
    external: true # add this if the network is already existing!