version: '3'

networks:
  frontend: 
    external: true # add this if the network is already existing!

services:
  rustdesk-server:
    container_name: rustdesk
    ports:
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21117:21117
      - 21118:21118
      - 21119:21119
    image: rustdesk/rustdesk-server-s6:latest
    environment:
      - "RELAY=rustdesk.example.com:21117"
      - "ENCRYPTED_ONLY=1"
      - "DB_URL=/db/db_v2.sqlite3"
      - "KEY_PRIV=FR2j78IxfwJNR+HjLluQ2Nh7eEryEeIZCwiQDPVe+PaITKyShphHAsPLn7So0OqRs92nGvSRdFJnE2MSyrKTIQ==PLEASE_CHANGE_ME"
      - "KEY_PUB=iEyskoaYRwLDy5+0qNDqkbPdpxr0kXRSZxNjEsqykyE=PLEASE_CHANGE_ME"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/db/rustdesk/data:/db
    restart: unless-stopped
    networks:
      - frontend
    dns: 172.20.0.250