version: "3"

networks:
  frontend:
    external: true # add this if the network is already existing!
#  backend:
#    external: true # add this if the network is already existing!

services:
  signal-cli-rest-api:
    image: bbernhard/signal-cli-rest-api:latest
    container_name: ${CONTNAME}
    environment:
      - MODE=normal #supported modes: json-rpc, native, normal
      #- AUTO_RECEIVE_SCHEDULE=0 22 * * * #enable this parameter on demand (see description below)
    ports:
      - "8080:8080" #map docker port 8080 to host port 8080.
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/container/${CONTNAME}/data:/home/.local/share/signal-cli
    networks:
      - frontend