version: '3.3'

networks:
  frontend:
    external: true # add this if the network is already existing!

services:
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: ${CONTNAME}
#    hostname: ${CONTNAME}
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/container/${CONTNAME}/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=${TRAEFIK}"
      - "traefik.http.routers.${CONTNAME}.entrypoints=http"
      - "traefik.http.routers.${CONTNAME}.rule=Host(`${CONTNAME}.${DOMAIN}`)"
      - "traefik.http.middlewares.${CONTNAME}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.${CONTNAME}.middlewares=${CONTNAME}-https-redirect"
      - "traefik.http.routers.${CONTNAME}-secure.entrypoints=https"
      - "traefik.http.routers.${CONTNAME}-secure.rule=Host(`${CONTNAME}.${DOMAIN}`)"
      - "traefik.http.routers.${CONTNAME}-secure.tls=true"
      - "traefik.http.routers.${CONTNAME}-secure.service=${CONTNAME}"
      - "traefik.http.services.${CONTNAME}.loadbalancer.server.port=3001"
      - "traefik.docker.network=proxy"
    ports:
      - ${WEBPORT}:3001
    networks:
      - frontend
    dns: 
      - 172.20.0.250