version: '3.8'
services:
  zerotier:
    image: zyclonite/zerotier
    container_name: ${CONTNAME}
    hostname: ${CONTNAME}
    devices:
      - /dev/net/tun
    network_mode: host
    volumes:
      - '/var/lib/zerotier-one:/var/lib/zerotier-one'
      - '/var/lib/zerotier-one/networks.d/${NETWORK_ID}.conf:/var/lib/zerotier-one/networks.d/${NETWORK_ID}.conf'
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    dns: 172.20.0.250