version: '3.8'

networks:
  frontend:
    external: true # add this if the network is already existing!

services:
  zerotier:
    image: zyclonite/zerotier:bridge
    container_name: ${CONTNAME}
    devices:
      - /dev/net/tun
    volumes:
      - '/var/lib/zerotier-one:/var/lib/zerotier-one'
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_ADMIN
    networks:
      - frontend
    dns: 172.20.0.250