version: '3.8'
services:
  zerotier:
    image: zyclonite/zerotier:bridge
    container_name: ${CONTNAME}
    hostname: ${CONTNAME}
    devices:
      - /dev/net/tun
    volumes:
      - '/var/lib/zerotier-one:/var/lib/zerotier-one'
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_ADMIN
    dns: 172.20.0.250